name: First_WorkFlow
on: workflow_dispatch
jobs: 
  firstjob:
    runs-on: ubuntu-latest
    steps:
      - name: Print Greetings
        run: echo "Hello world"
  secondjob:
    runs-on: ubuntu-latest
    steps:
      - name: Print Doodbye
        run: echo "I go to sleep"
